### ISSUE TITLE
What are the requirements for picking a settings.php

### ISSUE THREAD

**Issue by sovainfo** [WebKings-ca/gocomposer#3]
Currently it doesn't deal well with not having settings.php. In order to fix that I need to know the idea behind picking settings.php other than sites/default. Why would you not use sites/default/settings.php ?

**Comment by WebKings-ca** [comment]
Hi @sovainfo ,

I'm not sure I properly understand your question, but I will elaborate as much as I can:

1) The plug-in does use `sites/default/settings.php` to get the Database credentials.

2) If it fails to get the Database credentials from `sites/default/settings.php` directly, the fallback behaviour is to use drush to get them. If drush is not installed the plug-in auto-installs drush for this step.

3) If step#2 fails (which has never happened during testing) it will skip saving the environment variables in the `.env` file but complete the other functionality of this plug-in (convert the site to be fully composer managed).

As of today, I have re-tested the plug-in for the newly merged changes and it was working properly with the implementation from step# 1. I have tested it for both cases when `settings.local.php` is used and when it's not used.

Finally, the plug-in does have a feature for multi-sites where there can be database credentials for each sub-site, in that case it lists all the available `settings.php` files and the user can then specify which sub-site database credentials he wants to use.

I hope that answers your question... If you have any other comments please do let me know...

Thanks...

**Comment by sovainfo** [comment]
To put my query in perspective, I recommended GoComposer on D.O. twice now and both of them failed to use it. I consider GoComposer the only solution to the mess created with drupal/drupal. Too many fail to understand when to use drupal/drupal. Once they recognize their mistake, they still fail to recognize it can't be fixed by moving drupal/core to require.

Ran GoComposer on projects that weren't installed yet, running into syntax errors. Trying to fix that requires an understanding of the requirements. Read the code, wondering about the requirements in order to refactor, but not changing the requirements.

Understood from the code you can pick a sub-site, fail to understand why you would want that. Would expect an .env per sub-site and GoComposer to provide all of them.

But that might be for later, first priority is fixing the bugs.
- No settings.php should report and abort, not due to syntax error. Testing for the file doesn't work, the find command creates an empty file.

**Comment by WebKings-ca** [comment]
@sovainfo,

I think you misunderstood the purpose of this plug-in. The purpose of it is to convert _existing sites_ to the newly recommended template. And since existing sites have to have a `settings.php` file, the error you mentioned will not occur on existing Drupal 8 installs.

To install new sites the [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) is the recommended solution.

For now I'm closing this issue... Should you find any other bugs for the intended functionality of this plug-in please create a new issue.

**Comment by sovainfo** [comment]
In order to test gocomposer I created several environments. Yes, I forgot to install the site and gocomposer was so kind to inform me like this:

```
docker@cli:/var/www$ composer gocomposer

GoComposer is Initializing...
=============================


 Please Confirm: Composer.json file will be Created in /var/www (Recommended) (yes/no) [yes]:
 >

 Please Confirm: Your Original Site will be Backed up to the following directory:  /var/www/backup (Recommended) (yes/no) [yes]:
 >



  [ErrorException]
  Undefined offset: 0


gocomposer

docker@cli:/var/www$
```
If you are interested in improved error handling, just let me know, I'll create a PR
Refactored the code providing a message that sites/default/settings.php is missing.

**Comment by WebKings-ca** [comment]
Even though the error you mentioned will never occur for this plug-ins intended usage, you can go ahead and submit a new pull request for your proposed changes... as you said it will indicate the reason for this error, which is nice to have but in my opinion is not completely necessary...

Also, if you feel that you would like to extend the functionality of this plug-in for your use case you can fork the project and add your implementation..

**Comment by WebKings-ca** [comment]
@sovainfo,

I have revised my License for this project to the AGPL license... And as such I would request that the fork of my repo you have done to be fully deleted from your account. As such, I'm revoking permission for you forking my project.. If you would like to contribute please submit pull requests to this repo only.

The reason for the above action is after looking at your profile, it seams you have done the same thing with all of your repos on Github. You fork them and then fail to provide any contribution to the upstream repo. It seams to me this is done in bad faith so as to make it seam you're the original owner of other peoples work. Even though this repo is an open-source license repo, to abuse this privilege is a copy right infringement.  perfect example is the following forked repo:

[Forked Joomla repo](https://github.com/sovainfo/joomla-cms)

You have not made any contribution to this forked repo since October 2016, and it seams to me the only reason you still have is as mentioned above.
