### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by leetemp** [WebKings-ca/gocomposer#6]
I follow the instruction to upgrade my site, it was installed through the drupal/drupal template. after upgraded, I changed th root folder to "web" folder, . then that's what I got:

1: a blank front page with message : This page isn’t workingwww.mysite.com is currently unable to handle this request. HTTP ERROR 500

2:  error I got from my server,

[25-Sep-2019 16:48:18 UTC] PHP Fatal error: Uncaught Error: Class 'Drupal\Core\DrupalKernel' not found in /home/mysite/public_html/web/index.php:16
Stack trace:
#0 {main}
thrown in /home/mysite/public_html/web/index.php on line 16
[25-Sep-2019 16:49:11 UTC] PHP Warning: include(/home/mysite/public_html/vendor/composer/../../core/lib/Drupal/Core/DrupalKernel.php): failed to open stream: No such file or directory in /home/mysite/public_html/vendor/composer/ClassLoader.php on line 444
[25-Sep-2019 16:49:11 UTC] PHP Warning: include(): Failed opening '/home/mysite/public_html/vendor/composer/../../core/lib/Drupal/Core/DrupalKernel.php' for inclusion (include_path='/home/mysite/public_html/vendor/pear/archive_tar:/home/mysite/public_html/vendor/pear/console_getopt:/home/mysite/public_html/vendor/pear/pear-core-minimal/src:/home/mysite/public_html/vendor/pear/pear_exception:.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/mysite/public_html/vendor/composer/ClassLoader.php on line 444
[25-Sep-2019 16:49:11 UTC] PHP Fatal error: Uncaught Error: Class 'Drupal\Core\DrupalKernel' not found in /home/mysite/public_html/web/index.php:16
Stack trace:
#0 {main}
thrown in /home/mysite/public_html/web/index.php on line 16

please advise for what to fix this, thanks

**Comment by WebKings-ca** [comment]
>  I changed th root folder to "web" folder

Can you elaborate exactly how you changed the root folder to "web" folder?

**Comment by leetemp** [comment]
HI, webkings, I don't know, I am in the VPS, there is no way to do this in the UI, so I asked my hosting to do this for me, I don't know how he did this. I was told he "editing a userdata file" , is this related ?

**Comment by WebKings-ca** [comment]
@leetemp,

Thank you for your reply..

From the error you initially posted it seems your Drupal root has been set at `/home/mysite/public_html/web` i think setting it to `/home/mysite/web` should fix this issue... Otherwise, I would like to mention I highly recommend using the _GoComposer_ is to run it on a properly set up development environment such as your local computer...

I hope that solves your issue... I'll leave this issue open now for a bit for you to provide feedback if that works or not..

**Comment by leetemp** [comment]
Hi, Thanks
I asked my hosting to set the root in “/home/mysite/public_html/web”  because the default root for the site was “/home/mysite/public_html”  after gocomposer, it move to the /public_html/web"  

in all the VPS, the default root for domain is "home/mysite/public_html"  "mysite"is not the root, just a username of my account. so I guess I done the right thing, move to the public_html/web folder.

**Comment by WebKings-ca** [comment]
@leetemp , A couple of questions if you could provide the answer to:

1) In which environment did you run the _GoComposer Plugin_ ?

2) When you ran this plugin, did you get any errors?

**Comment by leetemp** [comment]
@webkings 
1:I am in the server with  CentOS 7.7 and apache 2.4, php7.2
2: as I remember, when I ran the gocomposer,  no error, just one off done.

**Comment by xaa** [comment]
it could be a simple permission issue. chmod 755 /web and other drupal folders

**Comment by WebKings-ca** [comment]
@leetemp,

From the following link:
[https://www.quora.com/What-is-centOS](url)

It appears you have ran the _GoComposer_ Plugin in your production environment.. As mentioned in the instructions, It should be run in your _Local Environment_.

As far as your original question, since I don't know how your web hosting account is setup, your web hosting provider should be able to inform you on how to point your domain name up one level to the `/Web` folder. This can be easily seen by the image below how the final folder structure will be after running the plugin...

Should you get any errors when running the  _GoComposer_ plugin on your local environment, Create another issue with the full output using Code tags... Closing this issue...
<img width="856" alt="New Folder Structure" src="https://user-images.githubusercontent.com/17931504/65794545-5d38d500-e136-11e9-9f1d-62e6cb904008.png">
